#
# "Startrek" app of apps configuration - "test" environment
#
applications:
  kirk:
    enabled: true
    enableAutoSync: true
    source:
      targetRevision: kamp
  spock:
    enabled: true
    source:
      targetRevision: kamp
