apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamp
  labels:
    app: kamp
spec:
  selector:
    matchLabels:
      app: kamp
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: kamp
    spec:
      containers:
      - name: kamp
        image: {{ .Values.account }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.image }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: "128m"
          requests:
            memory: 128Mi
            cpu: "80m"
