apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kamp
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.ssmDemoParamName }}
        objectType: ssmparameter
        jmesPath:
          - path: secret
            objectAlias: ssmdemoparamsecret
      - objectName: {{ .Values.asmDemoSecretName }}
        objectType: secretsmanager
        jmesPath:
          - path: secret
            objectAlias: asmdemosecret
