apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kamp
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.ssmDemoParamName }}
        objectType: ssmparameter
        jmesPath:
          - path: secret
            objectAlias: ssm-demo-param-secret
  # Note: This is to sync as K8s Secret and access through ENV vars
  secretObjects:
  - secretName: {{ .Values.asmDemoSecretName }}
    type: Opaque
    data:
    - objectName: asm-demo-secret
      key: secret
