apiVersion: v1
kind: Service
metadata:
  name: kamp
spec:
  selector:
    app: kamp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}   
  type: NodePort
