{{- range $key,$val := .Values.applications }}
# {{- /*
# in order to use tpl within a range, _and_ have the key/val available to sub-templates,
# need to add some variables to the root context.
# */ -}}
{{- $_ := set $ "appName" (print $.Values.environment "-" $key) }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.environment }}-{{ $key }}
  namespace: {{ $.Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $val.source.repoUrl }}
    targetRevision: {{ $val.source.targetRevision }}
    path: {{ $val.source.path }}
    helm:
      values:
      - environment: {{ $.Values.environment }}
      valueFiles:
      - values.yaml
      - values-{{ $.Values.environment }}.yaml
  destination:
    namespace: {{ $.Values.namespace }}
    server: {{ $.Values.default.destination.server }}
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
      - "PruneLast=true"
{{- if $val.enableAutoSync | default $.Values.default.enableAutoSync }}
    automated:
      prune: {{ $val.autoSyncPrune | default $.Values.default.autoSyncPrune | default true }}
{{- end }}
{{- end }}
{{- end }}
